### ISSUE TITLE
Connect Transforms

### ISSUE THREAD

**Issue by sergeiwaigant** [jcustenborder/kafka-connect-transform-common#29]
Hi there,

is it possible to use the "transform." properties in the Connector configuration?
We have issues when using your spooldir connector to import a CSV that has iso-8859-1 charset as avro message.
We want to transform to charset utf-8 before sending the avro message.

Any idea how to configure the connector then?

Regards
-Sergei

**Comment by jcustenborder** [comment]
@sergeiwaigant Sorry about the delay. I sometimes have issues seeing notifications. Take a look at the [transform documentation](https://kafka.apache.org/documentation/#connect_transforms) as a way to get started. As for spool dir have you looked at setting `csv.file.charset` to `UTF-8`? If this doesn't work you could write a transformation that converts each of the strings in the resulting struct to `UTF-8`
