### ISSUE TITLE
Transformations with Aggregations in Kafka

### ISSUE THREAD

**Issue by nidhijwt** [jcustenborder/kafka-connect-transform-common#63]
Hello,

I am trying to do following transformations 

```
"transforms": "BytesToString,ToJSON",
"transforms.BytesToString.type": "com.github.jcustenborder.kafka.connect.transform.common.BytesToString$Value",
"transforms.ToJSON.type": "com.github.jcustenborder.kafka.connect.transform.common.ToJSON$Value",
"transforms.BytesToString.delimiter": "_"
```
Along with Aggregations. The latest code in repo https://github.com/apache/camel-kafka-connector

```
"camel.beans.aggregate": "#class:org.apache.camel.kafkaconnector.aggregator.StringAggregator",
"camel.beans.aggregation.size": "3000",
"camel.beans.aggregation.timeout": "5000",
```

and it is giving error 

`java.lang.ClassNotFoundException: com.github.jcustenborder.kafka.connect.utils.config.ConfigKeyBuilder`

Though I have added all the dependencies. Do these transformations work with the latest version of the camel-kafka-connector code?

I checked this worked ok with earlier versions.

**Comment by jcustenborder** [comment]
Make sure that you are including the dependencies when you deploy. The output from `mvn clean package` creates a directory that has all of the dependencies. Deploy this as a subdirectory under what you have configured in the worker for `plugin.path`.
