### ISSUE TITLE
Conditional Transformation based on another Fields Value possible? Conversion Error Handling

### ISSUE THREAD

**Issue by lkaupp** [jcustenborder/kafka-connect-transform-common#74]
@jcustenborder is it possible to do a conditional transformation based on another field in the topic? Well i have an uniform log with value and datatype as columns. The value needs to be casted to the specified datatype specified in the the same message. I saw that predicates allow a specific field extraction and transformation but how to transform a field based on an other fields value?

e.g. { value: "8.88", datatype: "float" } => { value: 8.88, datatype: "float" }

and how to deal with conversion errors (logs are malformed)?

e.g. { value: "[True, false, true]": datatype: "boolean"} => Value is not a Boolean, so we have to try an array conversion and add an conditional field isArray => {value: [True, false, true], datatype: "boolean", isArray: true }

If an array transformation is not possible how can i flag that row with isMalformed: true?

Edit://
Tried to conditional transform the value, but now kafka-connect complains about the wrong schema. Because value, should be a string not a boolean....

**Comment by jcustenborder** [comment]
I'm not super familiar with [KIP-585](https://cwiki.apache.org/confluence/display/KAFKA/KIP-585%3A+Filter+and+Conditional+SMTs). I'd need to see the whole stack trace to know what is going on. In general I tend to use something like KSQL or Kafka Streams for this task.

**Comment by lkaupp** [comment]
can u point me to a source, how to convert a string datatype to something else using ksql? i know i could get all "boolean" tagged values in a select where clause, but how i transform these values?

**Comment by jcustenborder** [comment]
Maybe [cast](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#cast)?
