### ISSUE TITLE
ChangeTopicCase works strange

### ISSUE THREAD

**Issue by rkudryashov** [jcustenborder/kafka-connect-transform-common#91]
Hi, thanks for this library. I'm trying to lower case topic name: by default it is `outbox.event.Book`, and I want it to become `outbox.event.book`. (the topic name itself is created by [outbox event router SMT](https://debezium.io/documentation/reference/stable/transformations/outbox-event-router.html)). But after applying the following connector config:

```
    "transforms.topicCase.type": "com.github.jcustenborder.kafka.connect.transform.common.ChangeTopicCase",
    "transforms.topicCase.from": "UPPER_CAMEL",
    "transforms.topicCase.to"  : "LOWER_HYPHEN"
```

the topic name became `outbox.event.-book`

Also, if I use `LOWER_UNDERSCORE` topic name becomes `outbox.event._book`; by `LOWER_CAMEL` option topic name remains `outbox.event.Book`

I think the problem is that I need to convert only one part of the topic name

**Comment by jcustenborder** [comment]
hi @rkudryashov!

This particular transformation is a wrapper around google guava and [CaseFormat](https://guava.dev/releases/23.0/api/docs/com/google/common/base/CaseFormat.html). If you look at the enumeration it gives you some examples of what it will do. For example it handles the case of `TestTopic` to `test-topic` but doesn't have a format already to handle `Test.Topic`. I added a quick transform that should help you out. Take a look at [LowerCaseTopic](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-transform-common/transformations/LowerCaseTopic.html), this will take the string of a topic name and lowercase the whole string. This would handle the example you specified.

**Comment by rkudryashov** [comment]
Thanks @jcustenborder 

Also, how I can install the latest version? For example, the `0.1.0.54` version can be downloaded from https://www.confluent.io/hub/jcustenborder/kafka-connect-transform-common. Are you planning to publish the fix or do I need to build jar manually?

**Comment by rkudryashov** [comment]
Hi @jcustenborder

The library is updated on Confluent Hub, and I updated it in my local repository. But i didn't manage to install such a connector:

```json
{
  "name": "books-db-source-connector",
  "config": {
    "topic.prefix": "test123",
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "plugin.name": "pgoutput",
    "database.hostname": "books-db",
    "database.port": "5432",
    "database.user": "postgres",
    "database.password": "password",
    "database.dbname": "books",
    "database.server.name": "books",
    "table.include.list": "public.outbox",
    "heartbeat.interval.ms": "5000",
    "slot.name": "books_debezium",
    "publication.name": "books_publication",
    "transforms": "outbox,topicCase",
    "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
    "transforms.outbox.table.field.event.id": "uuid",
    "transforms.outbox.table.field.event.key": "aggregate_id",
    "transforms.outbox.route.by.field": "aggregate_type",
    "transforms.topicCase.type": "com.github.jcustenborder.kafka.connect.transform.common.ChangeTopicCase",
    "transforms.topicCase.from": "UPPER_CAMEL",
    "transforms.topicCase.to"  : "LOWER_CASE_TOPIC"
  }
}
```

The error is:

```json
{
    "error_code": 400,
    "message": "Connector configuration is invalid and contains the following 1 error(s):\nInvalid value 'LOWER_CASE_TOPIC' is not a valid value for CaseFormat. Valid values are LOWER_HYPHEN, LOWER_UNDERSCORE, LOWER_CAMEL, UPPER_CAMEL, UPPER_UNDERSCORE. for configuration to\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`"
}
```

**Comment by graesj** [comment]
Thought I'd chime in here as I just now encountered the same behavior (I'm also using debeizum's [EventRouter](https://debezium.io/documentation/reference/stable/transformations/outbox-event-router.html) for Outbox Pattern SMT). 

The LowerCaseTopic works well if it is a simple word in the final part like "Book" and I will use the same SMT for now. Are there plans to support "LOWER-UNDERSCORE" and "LOWER_HYPHEN" for the case outlined in this issue? For example: outbox.event.TestTopic -> outbox.event.test-topic (it currently becomes outbox.event.-test-topic)

Thanks for the library, it's very useful!
