### ISSUE TITLE
Redis Kafka Connect data not in order?

### ISSUE THREAD

**Issue by ranilkum** [jcustenborder/kafka-connect-transform-common#97]
Hi,
I tried to use simple 1 worker redis sink - but found at times the order of the data in kafka queue is not maintained. Is that meant to be in order?

**Comment by jcustenborder** [comment]
I think you opened this on the wrong project. This project is transformations. Are you thinking of [kafka-connect-redis](https://github.com/jcustenborder/kafka-connect-redis)? Kafka will process the data in the order of each partition. If your data is not keyed that could be the cause. There is no global order, only order by a partition.
